starttimeout: 5s
stoptimeout: 5s
http:
  address: 127.0.0.1:8080
  starttimeout: 1s
  stoptimeout: 1s
  writetimeout: 30s
aggregator:
  capacity: 1000
  barinterval: 60s
fakestreams: {
  BTC_USD: 100,
  ETH_USD: 20
}
fakestreamperiod: 60s
fakestreamminprice: 100
fakestreammaxprice: 1000
